### ISSUE TITLE
Change or remove font definition in frontmatter

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/the-ultimate-laser-guide#3]
@szaimen you can change the fonts here https://github.com/FH-Potsdam/the-ultimate-laser-guide/blob/5eae6ca2b9ea6cb995d45866c579666417fdb133/README.mdown?plain=1#L34-L44

related #2

**Comment by sebastian-meier** [comment]
this is not an issue. works fine. see current actions.

**Comment by szaimen** [comment]
> this is not an issue. works fine. 

Fine by me as long as it works :)

**Comment by sebastian-meier** [comment]
@szaimen When ever the Readme.md is updated the PDF will change automatically. It will need a little bit more visual finetuning. But works in general...
