### ISSUE TITLE
Update Laser Guide

### ISSUE THREAD

**Issue by sebastian-meier** [FH-Potsdam/the-ultimate-laser-guide#4]
Good morning @ff6347 @szaimen,

the laser guide is now automatically building upon any new commits to the main branch (renamed master to main). But the latest version of pandoc, latex, etc. are not fully compatible with the old layout. It took me a couple hours to get it working at all, but it looks 💩 right now. I have added the old PDF as a fallback to the repo. One major issue is, that the yaml frontmatter is not correctly interpreted for some reason. And some styling issues. I will try to get back to this ASAP...

**Comment by ff6347** [comment]
I remember adding manual page breaks to make this work look right(-ish). Maybe first thing would be to remove all occurrences of `\newpage` to see if this fixes some issues. 

What does look 💩 exactly?

**Comment by ff6347** [comment]
Maybe moving it directly into the README.mdown changes something or removing the `---` in the metadata.yaml does screw things up.

**Comment by sebastian-meier** [comment]
Bumping up the pandoc version to the latest 2.16.2 helped a bit. Now the fonts are acting up...

**Comment by sebastian-meier** [comment]
@ff6347 did you write the template.tex or adopt it from somewhere?

**Comment by ff6347** [comment]
It is the default template from pandoc with minor additions

**Comment by sebastian-meier** [comment]
After a lot of debugging it was this setting in the frontmatter `lang: de-DE` that messed everything up. It renders fine now, using IBM Plex as a font. When i have some time i will do some finetuning and see if i upgrade to the latest latex template. But for now i think its fine.

**Comment by sebastian-meier** [comment]
@ff6347 Thanks for the quick support!

**Comment by ff6347** [comment]
> @ff6347 Thanks for the quick support!

No problemo. Its you cleaning up my mess now. So we are even 😉
